# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Nantes 2015"
email: "bureau@gdgnantes.com"
description: "GDG DevFest is a set of events all around the world"
baseurl: "/zeppelin"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-35116426-1"
googleAnalyticsSiteUrl: "gdgnantes.com"
siteVerification: "4EEgOZ6RmVM4YVw1QNw-f8JuKIaHaDJ4HKLNRtfdntM"

# Organizer Info
organizerName: "GDG Nantes"
organizerAlternateName: "Google Developer Group Nantes"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "bureau@gdgnantes.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgnantes.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, nantes"
twitterAccount: "@gdgnantes"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Schedule"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest Nantes 2015, <typeout>"
eventDate: "6 Novembre, 2015"
typeoutTextValues: '"Cloud", "Objets connectés", "Web", "Découverte", "Networking", "Démos", "Conférences"'
typeoutFallback: "Conférences"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Devenez un speaker"}
 - {permalink: "/#tickets", text: "Acheter mon billet"}

# About Block
aboutTitle: "A propos des DevFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "participants", detail: "de partout"}
 - {count: "8", specialCharacter: "+", info: "heures", detail: "de pures conférences technologiques"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "de france et d'ailleurs"}
 - {count: "5", specialCharacter: "", info: "tracks paralleles", detail: "et aussi des stands de démos"}

# Latest News Block
latestNewsTitle: "Dernières news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "Voir tous les speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Cité des congrès"
eventLocationLink: "http://www.lacite-nantes.fr/fr/index.html"
eventStreetAddress: "Quai Ferdinand Favre"
eventAddressLocality: "Nantes"
eventAddressLocalityRegion: "Nantes"
eventPostalCode: "44000"
eventAddressCountry: "France"
eventStartTime: "2015-11-06T09:00"
eventDoorTime: "07:30"
eventEndTime: "2015-11-06T22:30"
eventPlaceCoordinates: "47.212966, -1.542565"
mapCenterCoordinates: "47.212966, -1.542565"
mapMobileCenterCoordinates: "47.212966, -1.542565"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Cité des congrès"
venueFeatures: ["4 grandes salles de conférences", "Un espace dédié aux démos", "à 5 minutes de la gare "]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Devenir un sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Pass Académique"
  price: "10"
  priceCurrency: "€"
  ticketsNumber: "80"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Acheter maintenant"
  additionalInfo: "Seul les personnes munies d'un justificatif en cours de validité seront acceptés le jour J."
  ticketContentList: ["Etudiants", "Enseignants", "Justificatif à présenter"]
  validFrom: "2015-06-15T10:00"
  validThrough: "2015-11-06T23:59"
 -
  name: "Pass Standard"
  price: "30"
  priceCurrency: "€"
  ticketsNumber: "430"
#  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Acheter maintenant"
  additionalInfo: "Seul le crédit temps du CPF sera pris en compte. Le prix du billet d'entrée ne sera pas rembourser dans le cadre du CPF"
  ticketContentList: ["Elligible au CPF"]
  validFrom: "2015-06-15T00:00"
  validThrough: "2015-11-06T23:59"
#  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/+GdgNantes", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=gdgnantes", icon: "twitter"}
 - {link: "https://facebook.com/GDGNantes", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://gdgnantes.com", text: "GDG Nantes"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bureau@gdgnantes.com", text: "bureau@gdgnantes.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Trouver votre chemin"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "47.212966, -1.542565"
logisticsMapMobileCenterCoordinates: "47.212966, -1.542565"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Venir à Nantes"
directionDetailsCards:
 - {title: "En train", information: "Nantes est à seulement 2h de Paris (Gare Montparnasse) en TGV.<br> Arrivé(e) à Nantes, prenez la sortie 'Gare Sud' puis vous serez à la Cité des Congrès en moins de 10 minutes à pied."}
 - {title: "Depuis l'aéroport", information: "L'aéroport est situé à l'extérieur de la ville. Pour Accéder à la cité des congrès, vous pouvez utiliser les <a href='http://www.nantes.aeroport.fr/acces/navettes' target='_blank'>navettes</a> (20 min), taxis ou louer une voiture."}
 - {title: "Transports en commun", information: "En tramway, prenez la ligne 1 : station <strong>'Duchesse Anne - Château des Ducs de Bretagne'</strong> à une station de la gare TGV (sortie Nord) <br> En busway, prenez la ligne 4 du busway et déscendez à l'arrêt <strong>'Cité des congrès'</strong>"}
 - {title: "En voiture", information: "La Cité des Congrès étant en plein centre ville, nous préconisons aux automobilistes de se garer sur un parking relais tram ou un parking payant. <br> La Cité des Congrès propose un <a href='http://www.parkings-nantes.fr/fr/stationner' target='_blank'>parking payant</a> de 450 places.<br> Pour voir les disponibilités des parkings en temps réel : <a href='http://parking-nantes.com/' traget='_blank'>http://parking-nantes.com/</a> <br> Liste des parkings relais : <a href='https://www.tan.fr/adminsite/objetspartages/liste_fichiergw.jsp?OBJET=DOCUMENT&CODE=1232704326125&LANGUE=0' target='_blank'>carte.pdf</a> ou directement sur le site de la <a href='https://www.tan.fr/jsp/fiche_pagelibre.jsp?CODE=07774142&LANGUE=0' target='_blank'>Tan</a>"}
 - {title: "Hotels", information: "<strong>Hôtel Résid'Home </strong><br>3 allée Jacques Berque<br>44000 Nantes<br>Situé juste en face de la Cité des Congrès, le Residhome les Berges de la Loire vous propose des tarifs négociés avec le code « DevFest2014 »."}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: false

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2015-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2015-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
