# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "DevFest Nantes 2015"
email: "bureau@gdgnantes.com"
description: "DevFest Nantes est une journée de conférences sur les technologies innovantes du moment"
baseurl: "/devfest"
url: "https://devfest.gdgnantes.com"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-35116426-1"
googleAnalyticsSiteUrl: "gdgnantes.com"
siteVerification: "4EEgOZ6RmVM4YVw1QNw-f8JuKIaHaDJ4HKLNRtfdntM"

# Organizer Info
organizerName: "GDG Nantes"
organizerAlternateName: "Google Developer Group Nantes"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "bureau@gdgnantes.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://gdgnantes.com/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, nantes"
twitterAccount: "@gdgnantes"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/DevFest_DossierSponsoring_2015.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Agenda"}
 - {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "L'équipe"}
 - {permalink: "/logistics/", text: "En Pratique"}
# - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Devenez un speaker"}
rightNavigationButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Devenez un speaker"}

# Hero Block
heroImage: "hero.jpg"
heroTitle: "DevFest Nantes 2015, <typeout>"
eventDate: "6 Novembre, 2015"
typeoutTextValues: '"Cloud", "Objets connectés", "Web", "Découverte", "Networking", "Démos", "Conférences"'
typeoutFallback: "Conférences"
heroButtons:
 - {link: "https://bit.ly/dfua-c4p", text: "Devenez un speaker"}
 - {permalink: "/#tickets", text: "Acheter mon billet"}

# About Block
aboutTitle: "A propos des DevFest"
aboutBlock:
 - {title: "Conférences", image: "conference.jpg", text: "Plsu de 28 conférences filmées (1h) autour de 4 thèmes : Web, Cloud, Objets Connectés, Découverte." }
 - {title: "CodeLab", image: "codelab.jpg", text: "Des codes labs, une occasion concrète de s'essayer à une technologie en compagnie d'un expert." }
 - {title: "Démo", image: "demo.jpg", text: "Des stands de démonstrations technologiques et innovations (Google Glass, Oculus Rift, Objets connectés)." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "600", specialCharacter: "+", info: "participants", detail: "de partout"}
 - {count: "28", specialCharacter: "+", info: "conférences", detail: "de pures conférences technologiques"}
 - {count: "30", specialCharacter: "+", info: "speakers", detail: "de France et d'ailleurs"}
 - {count: "5", specialCharacter: "", info: "tracks parallèles", detail: "et aussi des stands de démos"}

# Latest News Block
latestNewsTitle: "Dernières news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 3
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "Voir tous les speakers"

# Location Block
locationBlockTitle: "Localisation"
eventLocationName: "Cité des Congrès de Nantes"
eventLocationLink: "http://www.lacite-nantes.fr/"
eventStreetAddress: "Quai Ferdinand Favre"
eventAddressLocality: "Nantes"
eventAddressLocalityRegion: "Nantes"
eventPostalCode: "44000"
eventAddressCountry: "France"
eventStartTime: "2015-11-06T09:00"
eventDoorTime: "08:00"
eventEndTime: "2015-11-06T22:00"
eventPlaceCoordinates: "47.212966, -1.542565"
mapCenterCoordinates: "47.212966, -1.542565"
mapMobileCenterCoordinates: "47.212966, -1.542565"

# Venue Block
venueBlockTitle: "L'espace"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Cité des congrès"
venueFeatures: ["4 grandes salles de conférences", "Un espace dédié aux démos", "à 5 minutes de la gare "]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organisateurs"
partnersTitle: "Sponsors"
partnersC4sponsorsButton: "Devenir un sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Inscrivez vous à la newsLetter"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Les inscriptions seront ouvertes début juin. Le nombre de places est limité. Restez connecté ! "

# Tickets Block
ticketsTitle: "Tarifs"
ticketsInfo: "Les billets vous donnent un accès complet aux conférences, au petit déjeuner, au repas ainsi qu'à l'After party."
ticketsOffers:
 -
  name: "Pass Académique"
  price: "10"
  priceCurrency: "€"
  ticketsNumber: "80"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Acheter maintenant"
  additionalInfo: "Seul les personnes munies d'un justificatif en cours de validité seront acceptés le jour J."
  ticketContentList: ["Etudiants", "Enseignants"]
  validFrom: "2015-06-15T10:00"
  validThrough: "2015-11-06T23:59"
  soldOut: false
  soldOutText: "Sold Out"
 -
  name: "Pass Standard"
  price: "30"
  priceCurrency: "€"
  ticketsNumber: "430"
#  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Acheter maintenant"
  additionalInfo: "Seul le crédit temps du CPF sera pris en compte. Le prix du billet d'entrée ne sera pas rembourser dans le cadre du CPF"
  ticketContentList: ["Elligible au CPF", "Pass standard"]
  validFrom: "2015-06-15T00:00"
  validThrough: "2015-11-06T23:59"
  soldOut: false
  soldOutText: "Sold Out"
#  disabled: true

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/+GdgNantes", icon: "google-plus"}
 - {link: "https://twitter.com/gdgnantes", icon: "twitter"}
 - {link: "https://facebook.com/GDGNantes", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Liens"
  links:
   - {link: "http://gdgnantes.com", text: "GDG Nantes"}
   - {link: "https://developers.google.com", text: "Google Developers"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:bureau@gdgnantes.com", text: "bureau@gdgnantes.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Dernières news"
blogCommentsEnabled: true
discusShortName: "devfestnantes"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "A propos"
aboutUs: "Les Google Developer Groups (GDGs) sont des groupes de développeurs intéressés par les technologies Google : GWT, Android, App Engine, les APIs Google, mais également les techno du Web comme HTML5, CSS3... Nous nous intéressons à tout type de techno que ce soit dans le domaine de la mobilité, du cloud ou du web. <br><br><h4>Le GDG Nantes</h4> <br>L’objectif du GDG Nantes est d’organiser des évènements de manière régulière : <ul><li>Conférences sur les technologies Google, Web ...</li><li>Des apéros ;) autour de sujets centraux afin de se rencontrer et boire un verre ensemble</li><li>Des concours (Hackathon...)</li></ul><br>Le GDG Nantes est également partenaire d’évènements nationaux ou d'autres communautés tels que les JUG."

# Logistics Find Way Block
findWayTitle: "Comment s'y rendre"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "47.212966, -1.542565"
logisticsMapMobileCenterCoordinates: "47.212966, -1.542565"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Venir à Nantes"
directionDetailsCards:
 - {title: "En train", information: "Nantes est à seulement 2h de Paris (Gare Montparnasse) en TGV.<br> Arrivé(e) à Nantes, prenez la sortie 'Gare Sud' puis vous serez à la Cité des Congrès en moins de 10 minutes à pied."}
 - {title: "Depuis l'aéroport", information: "L'aéroport est situé à l'extérieur de la ville. Pour Accéder à la cité des congrès, vous pouvez utiliser les <a href='http://www.nantes.aeroport.fr/acces/navettes' target='_blank'>navettes</a> (20 min), taxis ou louer une voiture."}
 - {title: "Transports en commun", information: "En tramway, prenez la ligne 1 : station <strong>'Duchesse Anne - Château des Ducs de Bretagne'</strong> à une station de la gare TGV (sortie Nord) <br> En busway, prenez la ligne 4 du busway et déscendez à l'arrêt <strong>'Cité des congrès'</strong>"}
 - {title: "En voiture", information: "La Cité des Congrès étant en plein centre ville, nous préconisons aux automobilistes de se garer sur un parking relais tram ou un parking payant. <br> La Cité des Congrès propose un <a href='http://www.parkings-nantes.fr/fr/stationner' target='_blank'>parking payant</a> de 450 places.<br> Pour voir les disponibilités des parkings en temps réel : <a href='http://parking-nantes.com/' traget='_blank'>http://parking-nantes.com/</a> <br> Liste des parkings relais : <a href='https://www.tan.fr/adminsite/objetspartages/liste_fichiergw.jsp?OBJET=DOCUMENT&CODE=1232704326125&LANGUE=0' target='_blank'>carte.pdf</a> ou directement sur le site de la <a href='https://www.tan.fr/jsp/fiche_pagelibre.jsp?CODE=07774142&LANGUE=0' target='_blank'>Tan</a>"}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "http://www.residhome.com/", text: "Résid Home (code de réduction DevFest2015)"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

